### ISSUE TITLE
Task #1

### ISSUE THREAD

**Issue by ghost** [mpilkou/LeverX#1]
1. It's better to use arg parser instead of sys arg.

2. It's better to dataclass for Room and Student objects.

3. Seems like Controller has a lot of power, it's almost a god object. Fix it according to SOLID principles. (you can start from moving export logic to separate classes)

**Comment by mpilkou** [comment]
1. Done
2. Now export works much more slower, you can see this done in folder [https://github.com/mpilkou/LeverX/tree/master/task%201/task%201%20with%20dataclass](url)

3. Done
